"""Initial migration.

Revision ID: 0d040f43af6b
Revises: 0afc782f4cac
Create Date: 2023-08-15 01:31:06.695030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d040f43af6b'
down_revision = '0afc782f4cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STAFF', 'ADMIN', 'NORMAL_USER', name='userrole'), nullable=True),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_type')
    # ### end Alembic commands ###
