"""Initial migration.

Revision ID: 546de46f2a12
Revises: 5f8d9028c81e
Create Date: 2023-08-10 00:37:59.548640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546de46f2a12'
down_revision = '5f8d9028c81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
